name: yemekhane
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Bu blok en soldan başlamalı!
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/atu_logo_icon.png" # Assets kısmındaki isimle aynı yaptım
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/atu_logo.png
