// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAF1tU7qfPoIwF1zlEC4EhVzND5GduyxQ',
    appId: '1:1012198286212:web:36df843b88b9d6a32a33d1',
    messagingSenderId: '1012198286212',
    projectId: 'first-project-42720',
    authDomain: 'first-project-42720.firebaseapp.com',
    storageBucket: 'first-project-42720.firebasestorage.app',
    measurementId: 'G-1S9QELHHSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCdMOpFFkx85SfhdLfilBOv2YWfweuQU',
    appId: '1:1012198286212:android:c1f345c072d1c2722a33d1',
    messagingSenderId: '1012198286212',
    projectId: 'first-project-42720',
    storageBucket: 'first-project-42720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdgrJ5RjXm8COJ0W4scV9cmM4pn7JIkM',
    appId: '1:1012198286212:ios:002e6b665862edd92a33d1',
    messagingSenderId: '1012198286212',
    projectId: 'first-project-42720',
    storageBucket: 'first-project-42720.firebasestorage.app',
    iosBundleId: 'com.example.gdgCampusCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdgrJ5RjXm8COJ0W4scV9cmM4pn7JIkM',
    appId: '1:1012198286212:ios:002e6b665862edd92a33d1',
    messagingSenderId: '1012198286212',
    projectId: 'first-project-42720',
    storageBucket: 'first-project-42720.firebasestorage.app',
    iosBundleId: 'com.example.gdgCampusCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAF1tU7qfPoIwF1zlEC4EhVzND5GduyxQ',
    appId: '1:1012198286212:web:f051ecbe4b276bf42a33d1',
    messagingSenderId: '1012198286212',
    projectId: 'first-project-42720',
    authDomain: 'first-project-42720.firebaseapp.com',
    storageBucket: 'first-project-42720.firebasestorage.app',
    measurementId: 'G-9YK3WSL9K2',
  );
}
